spring:
  kafka:
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
     consumer: 
       group-id: test1

kafka-listeners:
  -
    topics: [test]
    auto-startup: true
#    topic-partitions:
#      -
#        topic: test
#        partition-offsets:
#          -
#            partition: 0
#            initial-offset: 2    


